spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false
  datasource:
    password: root
    username: root
    url: jdbc:mysql://localhost:3306/defenestratio?useSSL=false
server:
  port: 8080
